#!/bin/bash

# chef init script
# basic init script for chef

# chef-client -d -s 60 -l info -L /var/log/chef-client.log -p /var/run/chef-client.pid

export LOGFILE="/var/log/chef-client.log"
export PIDFILE="/var/run/chef-client.pid"
export CHEF="/usr/bin/chef-client"

start()
{
	if [ -f "$CHEF" ]; then
		echo -n "Starting Chef .."
		$CHEF -d -s 60 -l info -L $LOGFILE -p $PIDFILE
		touch /var/lock/subsys/chef
		echo "done"
	else
		echo "Chef not installed (${CHEF}), cannot continue"
		exit 1
	fi
}

stop()
{
	if [ -f "$PIDFILE" ]; then
		echo -n "Stopping Chef..."
		kill -TERM `cat $PIDFILE`
		sleep 2
		[ -f "$PIDFILE" ] && echo "Chef did not go down, trying harder" && kill -9 `cat $PIDFILE`
		rm -f /var/lock/subsys/chef
		echo "done"
	else
		echo "Chef PID file not present (${PIDFILE}), check the process list yourself"
	fi
}

status()
{
	if [ -f "$PIDFILE" ]; then
		export PID=`cat $PIDFILE`
		echo "PID ${PID} found..."
		ps auxw | grep $PID | grep -v grep
	else
		echo "Chef PID file not present (${PIDFILE}), check the process list yourself"
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status
		;;
        *)
	echo $"Usage: $0 {start|stop|restart|status}"
	RETVAL=1
esac

