##
# Automated backup system for mysql slaves.
#
# @author   Bryan Kroger ( bryan@lockerz.com )
# @copyright 2011 lockerz.com
include_recipe "mysql::default"

## User setup
user = search( :lockerz,"id:users" ).first["mysqlbackup@lockerz.com"]
user_dir do
	username "mysqlbackup"
	private_key user["private_key"]
end

mdadm "/dev/md0" do
	level 0
	action [ :create, :assemble ]
	devices ["sdb","sdc"]
end

mount "/mnt/local" do 
	device "/dev/md0"
end

directory "/var/run/mysqlbackup" do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
end

## Logging container
directory node[:mysqlBackup][:fsLogRoot] do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
	action :create
	recursive true
end

## Data container
directory node[:mysqlBackup][:fsDataRoot] do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
	action :create
	recursive true
end

cookbook_file "/home/mysqlbackup/scripts/snapshot_ebs.rb" do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
	source "snapshot_ebs.rb"
end

cookbook_file "/home/mysqlbackup/ec2/pk.pem" do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
	source "pk.pem"
end

cookbook_file "/home/mysqlbackup/ec2/cert.pem" do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
	source "cert.pem"
end

cookbook_file "/home/mysqlbackup/.bashrc" do
	mode "0755"
	owner "mysqlbackup"
	group "mysqlbackup"
	source "backup/bashrc"
end

## Iterate through the list of slaves.
#slaves = search( :node,"chef_environment:%s AND run_list:role\\[MySQLSlave\\]" % node.chef_environment )
#slaves.each do |slaveNode|
	#puts "Slave: %s" % slaveNode[:fqdn]
	#mysql_backup_script do
		#targetNode slaveNode
	#end
#end

# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.rlerV4/crontab installed on Fri Oct 28 16:30:01 2011)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
# m h  dom mon dow   command
#MAILTO=larry@lockerz.com
# m h  dom mon dow   command
#1 * * * *  sh -x /usr/local/bin/lockerz/membk.sh  > /ebs/mysql-misc/cronlog/membk.log   2>&1

#15 6 * * *  /usr/local/bin/lockerz/vol_desc_all.sh  14400  > /ebs/mysql-misc/cronlog/vol_desc_all.log   2>&1

# check all mysql vital signs
#50 * * * *  /usr/local/bin/lockerz/db_vital_sign.sh >> /ebs/mysql-misc/cronlog/db_vital_sign.log 2>&1 

#LmTool
#25 6 * * *  /usr/local/bin/lockerz/krun_remote.sh LmTool "hostname; /usr/local/bin/lockerz/kmysqldump_nrt.sh mysql   >> /ebs/mysql-misc/cronlog/bk_mysql.log "  >> /ebs/mysql-misc/cronlog/bk_LmTool_mysql.log 2>&1
#25 6 * * *  /usr/local/bin/lockerz/krun_remote.sh LmTool "hostname; /usr/local/bin/lockerz/kmysqldump_nrt.sh bos   >> /ebs/mysql-misc/cronlog/bk_bos.log "  >> /ebs/mysql-misc/cronlog/bk_LmTool_bos.log 2>&1
#25 18 * * *  /usr/local/bin/lockerz/krun_remote.sh LmTool "hostname; /usr/local/bin/lockerz/kmysqldump_nrt.sh bos   >> /ebs/mysql-misc/cronlog/bk_bos.log "  >> /ebs/mysql-misc/cronlog/bk_LmTool_bos.log 2>&1

#1 8 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxForu "hostname; /usr/local/bin/lockerz/kmysqldump.sh mysql   >> /ebs/mysql-misc/cronlog/bk_mysql.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxForu_mysql.log 2>&1
#3 8 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxForu "hostname; /usr/local/bin/lockerz/kmysqldump.sh forum   >> /ebs/mysql-misc/cronlog/bk_forum.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxForu_forum.log 2>&1

#1 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxComm "hostname; /usr/local/bin/lockerz/kmysqldump.sh mysql   >> /ebs/mysql-misc/cronlog/bk_mysql.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxComm_mysql.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxComm "hostname; /usr/local/bin/lockerz/kmysqldump.sh magento   >> /ebs/mysql-misc/cronlog/bk_magento.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxComm_magento.log 2>&1
#8 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxComm "hostname; /usr/local/bin/lockerz/kmysqldump.sh pim   >> /ebs/mysql-misc/cronlog/bk_pim.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxComm_pim.log 2>&1

#1 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxLoca "hostname; /usr/local/bin/lockerz/kmysqldump.sh mysql   >> /ebs/mysql-misc/cronlog/bk_mysql.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxLoca_mysql.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxLoca "hostname; /usr/local/bin/lockerz/kmysqldump.sh bits   >> /ebs/mysql-misc/cronlog/bk_bits.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxLoca_bits.log 2>&1
#5 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxLoca "hostname; /usr/local/bin/lockerz/kmysqldump.sh locator   >> /ebs/mysql-misc/cronlog/bk_locator.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxLoca_locator.log 2>&1

#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod1 "hostname; /usr/local/bin/lockerz/kmysqldump.sh pod1   >> /ebs/mysql-misc/cronlog/bk_pod1.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxPod1_pod1.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod2 "hostname; /usr/local/bin/lockerz/kmysqldump.sh pod2   >> /ebs/mysql-misc/cronlog/bk_pod2.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxPod2_pod2.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod3 "hostname; /usr/local/bin/lockerz/kmysqldump.sh pod3   >> /ebs/mysql-misc/cronlog/bk_pod3.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxPod3_pod3.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod4 "hostname; /usr/local/bin/lockerz/kmysqldump.sh pod4   >> /ebs/mysql-misc/cronlog/bk_pod4.log "  >> /ebs/mysql-misc/cronlog/bk_Savxxod4_pod4.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod5 "hostname; /usr/local/bin/lockerz/kmysqldump.sh pod5   >> /ebs/mysql-misc/cronlog/bk_pod5.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxPod5_pod5.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod6 "hostname; /usr/local/bin/lockerz/kmysqldump.sh pod6   >> /ebs/mysql-misc/cronlog/bk_pod6.log "  >> /ebs/mysql-misc/cronlog/bk_SavxxPod6_pod6.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxMedi "hostname; /usr/local/bin/lockerz/kmysqldump.sh media  >> /ebs/mysql-misc/cronlog/bk_media.log " >> /ebs/mysql-misc/cronlog/bk_SavxxMedi_medi.log 2>&1
#9 7 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxMedi "hostname; /usr/local/bin/lockerz/kmysqldump.sh video  >> /ebs/mysql-misc/cronlog/bk_video.log " >> /ebs/mysql-misc/cronlog/bk_SavxxMedi_video.log 2>&1

#3 9 * * *  /usr/local/bin/lockerz/krun_remote.sh SavAucProxy "hostname; /usr/local/bin/lockerz/kmysqldump.sh auction_proxy  >> /ebs/mysql-misc/cronlog/bk_auction_proxy.log "   >> /ebs/mysql-misc/cronlog/bk_SavAucProxy_auction_proxy.log 2>&1
#3 9 * * *  /usr/local/bin/lockerz/krun_remote.sh SavAucProxy "hostname; /usr/local/bin/lockerz/kmysqldump.sh user_auction  >> /ebs/mysql-misc/cronlog/bk_user_auction.log "   >> /ebs/mysql-misc/cronlog/bk_SavAucProxy_user_auction.log 2>&1
#3 9 * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxAuction "hostname; /usr/local/bin/lockerz/kmysqldump.sh auction  >> /ebs/mysql-misc/cronlog/bk_auction.log "   >> /ebs/mysql-misc/cronlog/bk_SavxxAuction_auction.log 2>&1

#1 7 * * *  /usr/local/bin/lockerz/krun_remote.sh MasRepo "hostname; /usr/local/bin/lockerz/kmysqldump.sh mysql   >> /ebs/mysql-misc/cronlog/bk_mysql.log "  >> /ebs/mysql-misc/cronlog/bk_MasRepo_mysql.log 2>&1
#3 7 * * *  /usr/local/bin/lockerz/krun_remote.sh MasRepo "hostname; /usr/local/bin/lockerz/kmysqldump.sh magento   >> /ebs/mysql-misc/cronlog/bk_magento.log "  >> /ebs/mysql-misc/cronlog/bk_MasRepo_magento.log 2>&1

# Clean up available volume at 9AM PDT evey 2 days
# 1 16 */2 * *  /usr/local/bin/lockerz/del_vol.sh >> /ebs/mysql-misc/cronlog/del_vol.log 2>&1
# Snapshot Backup and Clean up 
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxMedi "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxMedi_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxForu "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxForu_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxComm "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxComm_ksnap.log 2>&1
#4 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxLoca "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxLoca_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod1 "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxPod1_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod2 "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxPod2_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod3 "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxPod3_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod4 "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxPod4_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod5 "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxPod5_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxPod6 "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxPod6_ksnap.log 2>&1
#3 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh MasRepo   "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/MasRepo_ksnap.log 2>&1
#9 0-23/4  * * *  /usr/local/bin/lockerz/krun_remote.sh SavxxSoca "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxSoca_ksnap.log 2>&1
#14 0-23/4  * * * /usr/local/bin/lockerz/krun_remote.sh SavAucProxy "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882 > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavAucProxy_ksnap.log 2>&1
#14 0-23/4  * * * /usr/local/bin/lockerz/krun_remote.sh SavxxAuction "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 2882 > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/SavxxAuction_ksnap.log 2>&1
#15 8 * * *  /usr/local/bin/lockerz/krun_remote.sh DwttMaster "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 9000   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/DwttMaster_ksnap.log 2>&1
#25 8 * * *  /usr/local/bin/lockerz/krun_remote.sh JasperMaster "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 9000   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/Jasp_ksnap.log 2>&1
#15 8 * * *  /usr/local/bin/lockerz/krun_remote.sh AutoxxRestore "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 1440   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/AutoxxRestore_ksnap.log 2>&1
#20 8 * * *  /usr/local/bin/lockerz/krun_remote.sh ETLxxMaster "hostname; /usr/local/bin/lockerz/ksnap_bk_wrap.sh 9000   > /var/log/ksnap/ksnap_bk.log 2>&1"  >> /ebs/mysql-misc/cronlog/ETLxxMaster_ksnap.log 2>&1
#TMP

