#! /usr/bin/python

# Python ICE module was compiled from source - the ubuntu packages seem
# to have a version mismatch between the python interpreter and the
# ICE libraries
#
# to pre-compile the phoenix.ice slice file requires the slice2python app
# the phoenix.ice file needs to be recompiled if the interfaces change

import sys
sys.path.append('/opt/Ice-3.3.1/python')
sys.path.append('/usr/phoenix')

def OK(msg):
        """exit OK"""
        print "OK: %s"%(msg)
        sys.exit(0)

def WARN(msg):
        """exit WARNING"""
        print "WARNING: %s"%(msg)
        sys.exit(1)

def CRIT(msg):
        """exit CRITICAL"""
        print "CRITICAL: %s"%(msg)
        sys.exit(2)

def UNKNOWN(msg):
        """exit UNKNOWN"""
        print "UNKNOWN: %s"%(msg)
        sys.exit(3)


import Ice
from com.lockerz.phoenix import slice

import socket
import time

hostName=sys.argv[1]

# Fire up ICE
comm=None
comm=Ice.initialize()
ip=socket.gethostbyname(hostName)

# grab hold of the proxy for the services we want to talk to
AuctionProxyServiceAdmin=slice.auctions.AuctionProxyServiceAdminPrx.checkedCast(comm.stringToProxy("AuctionProxyServiceAdmin:tcp -h %s -p 12350"%( hostName)))

# Get the a count of all LIVE auctions for the response
auctionLiveCount=AuctionProxyServiceAdmin.getAllAuctionsOfStatusCount(slice.auctions.AuctionStatus.Live)
# Get a list of all LIVE auctions
auctions=AuctionProxyServiceAdmin.getAllAuctionsOfStatusPage(slice.auctions.AuctionStatus.Live,0,auctionLiveCount)
# Current Time
currentTime=time.time()*1000
# Loop through looking for any with an end time in the past
crits=[]
for k in auctions:
	if k.endTime<currentTime:
		crits.append("%d(%d)"%(k.id, k.endTime))

if comm:
    # Clean up
    try:
        comm.destroy()
    except:
	UNKNOWN("Internal error during cleanup")

# Any failed?
if crits:
	CRIT("%d auctions end earlier than %d for auctions: %s"%(len(crits), int(currentTime), ', '.join(crits)))

OK("%d Live auctions end after now."%(auctionLiveCount))
