#!/bin/sh

HOST=$1
DEBUG=0
DI=/tmp/di.out
KNL=/tmp/knl.out




Usage()
{
	echo -e "\nUSAGE:  $0"
	echo -e "     --> interactive mode to choose host"
	echo -e "\nUSAGE:  $0  <hostname>"
	echo -e "     --> return all data on <hostname>"
	exit 0;
}


Fatal()
{
	echo -e "\nFATAL:  $*"
	exit 1;
}



Debug()
{
	if [ $DEBUG -gt 0 ]; then
		echo "DEBUG:  $*"
	fi
	#exec $*
}




### Begin Main Script


	TODAY=$(date | awk '{print $3}')
	DIDAY=$(ls -al $DI | awk '{print $7}')
	if [ $TODAY -ne $DIDAY ];then
		Debug "removing stale decribe-instances file $DI"
		#rm -f $DI
	elif [ ! -s $DI ];then
		Debug "removing empty decribe-instances file $DI"
		rm -f $DI
	else
		Debug "decribe-instances file $DI is up to date"
		ls -al $DI
	fi


	case $HOST in 

	-help|--help|help|-h|--h|-H|--H)
		Usage
		;;

	"")
		echo -e "Please select a hostname (enter just base node name, not FQDN):\n"
		if [ ! -f $KNL ];then
			knife node list > $KNL
		fi
		if [ ! -s $KNL ];then
			Fatal "knife node list $KNL not valid."
		fi
		cat  $KNL
		echo
		read HOST

		Debug "interactive usage"
		;;

	*)
		Debug "standard usage"
		;;


	esac


	if [ "$HOST" = "" ];then
		Fatal "must enter a host."
	fi
	HO=/tmp/$HOST.out
	
	
	IP=$(nslookup $HOST | tail -3 | grep Address | awk '{print $2}')
	if [ "$IP" = "" ];then
		Fatal "hostname [$HOST] not found."
	fi
	
	if [ ! -f $DI ]; then
		Debug "ec2-describe-instances --show-empty-fields > $DI"
		ec2-describe-instances --show-empty-fields > $DI
		chmod 777 $DI
	else
		Debug "using pre-existing $DI"
	fi
	
	Debug "grep $IP $DI"
	AWS_ID=`grep $IP $DI | awk '{print $2}'`
	if [ "$AWS_ID" = "" ];then
		Fatal "AWS_ID is NULL"
	fi
	
	if [ ! -f $HO ]; then
		Debug "ec2-describe-instances --show-empty-fields $AWS_ID > $HO"
		echo -e "\n\n\nEC2 Describe Instance $AWS_ID\n----------------------------------\n" >> $HO
		ec2-describe-instances --show-empty-fields $AWS_ID >> $HO
		echo -e "\n\n\nFilesystem info:  df -k \n----------------------------------\n" >> $HO
		ssh root@$HOST df -k >> $HO
	
	else
		Debug "using pre-existing $HO"
	fi
	
	
	
	Debug "grep $IP $DI"
	#awk "{ print \" HOST:  $HOST\n Int IP: $IP\n Ext IP: \",\$14, \"\n Zone: \", \$11,\"\n\"}"
	echo -e "\n===========================\nHOST:  $HOST \n===========================\n"
	echo "  Int IP:   $IP"
	grep $IP $DI |  awk '{print "  Ext IP:  ",$17 ,"\n  Zone:    ",$12, "\n  Machine: ",$10}'
	echo "  AWS ID:   $AWS_ID"
	echo "  Other :"
	cat $HO
	
	
