#!/bin/bash

set -e 

SCRIPTS_DIR=`readlink -f $(dirname $0)`
PATH="${PATH}:${SCRIPTS_DIR}"

source $(dirname $0)/include

PEGASUS_REMOTE=origin
PEGASUS_BASE_BRANCH=develop

shift $(($OPTIND - 1))

if test $# -lt 1; then
    fatal "One argument, the version number, is required"
fi


VERSION=$1
#RELEASE_BRANCH="release-$VERSION"
GIT_TAG="${VERSION}"

info "Building pegasus version $1"
cd ${PEGASUS_BUILD_HOME};

info "Setting asset version in config_prod.yml"
cat config/config_prod.yml | set-pegasus-asset-version $VERSION > config/config_prod.yml.tmp
mv config/config_prod.yml.tmp config/config_prod.yml
git commit -am "Setting asset version"
git push ${LOCKERZ_REMOTE} master

echo "Updating vendors"
php bin/vendors.php install

echo "Cleaning cache, log, web/bundles"
sudo rm -rf cache/*
sudo rm -rf logs/*
sudo rm -rf web/bundles

echo "Running assets:install"
php bin/console -e=prod --no-debug assets:install web
echo "Running assetic:dump"
php bin/console -e=prod --no-debug assetic:dump
echo "Compressing dumped assets"
bin/compress_assets.sh
echo "uploading assets to s3"
s3cmd -P -r put web/bundles/* s3://lockerz-static/pegasus/${VERSION}/bundles/

sudo chmod -R 777 cache
sudo chmod -R 777 logs






