#!/bin/bash

set -e 

SCRIPTS_DIR=`readlink -f $(dirname $0)`
PATH="${PATH}:${SCRIPTS_DIR}"

source $(dirname $0)/include

PEGASUS_REMOTE=origin
PEGASUS_BASE_BRANCH=develop

shift $(($OPTIND - 1))

if test $# -lt 1; then
    fatal "One argument, the version number, is required"
fi


VERSION=$1
#RELEASE_BRANCH="release-$VERSION"
GIT_TAG="${VERSION}"

info "Building pegasus version $1"
info "PEGASUS_BUILD_HOME is ${PEGASUS_BUILD_HOME}"
cd ${PEGASUS_BUILD_HOME};

echo "Updating git and reseting develop"
git checkout ${PEGASUS_BASE_BRANCH};
git fetch ${PEGASUS_REMOTE}
git reset --hard ${PEGASUS_REMOTE}/${PEGASUS_BASE_BRANCH}


if test ! -z `git tag | grep ${VERSION}`; then
    fatal "There is already a tag named ${VERSION}"
fi

#info "Creating release branch: ${RELEASE_BRANCH}"
#git checkout -b ${RELEASE_BRANCH}

echo $PATH
info "Setting asset version in config_prod.yml"
cat config/config_prod.yml | set-pegasus-asset-version $VERSION > config/config_prod.yml.tmp
mv config/config_prod.yml.tmp config/config_prod.yml
git commit -am "Setting asset version"
git push ${PEGASUS_REMOTE} develop
#git push ${PEGASUS_REMOTE} ${RELEASE_BRANCH}
git tag -a ${GIT_TAG} -m "Release of version ${VERSION}"
git push ${PEGASUS_REMOTE} ${GIT_TAG}

echo "Updating vendors"
php bin/vendors.php install

echo "Cleaning cache, log, web/bundles"
sudo rm -rf cache/*
sudo rm -rf logs/*
sudo rm -rf web/bundles

#echo "Running cache:clear"
#php bin/console -e=prod --no-debug cache:clear
echo "Running assets:install"
php bin/console -e=prod --no-debug assets:install web
echo "Running assetic:dump"
php bin/console -e=prod --no-debug assetic:dump
echo "Compressing dumped assets"
bin/compress_assets.sh
echo "uploading assets to s3"
s3cmd -P -r put web/bundles/* s3://lockerz-static/pegasus/${VERSION}/bundles/

sudo chmod -R 777 cache
sudo chmod -R 777 logs






