#!/bin/bash

set -e

source $(dirname $0)/include

shift $(($OPTIND - 1))

if test $# -lt 2 ; then
  fatal "At least two arguments are required"
fi

VERSION=$1
HOST=$2

cd ${PEGASUS_BUILD_HOME}
ssh ubuntu@${HOST} "sudo service apache2 stop"
rsync --progress --exclude=.git -az . ubuntu@${HOST}:/home/ubuntu/opt/pegasus
ssh ubuntu@${HOST} "sudo rm -rf /home/ubuntu/opt/pegasus/cache/*"
ssh ubuntu@${HOST} "cd /home/ubuntu/opt/pegasus; php bin/console -e=prod --no-debug cache:clear;"
ssh ubuntu@${HOST} "sudo chmod -R 777 /home/ubuntu/opt/pegasus/cache"



ssh ubuntu@${HOST} "sudo service apache2 start"