#!/bin/bash

LOCKERZ_BUILD_HOME=/home/ubuntu/build/repos/lockerz
PLATZ_BUILD_HOME=${LOCKERZ_BUILD_HOME}/platz
PEGASUS_BUILD_HOME=${LOCKERZ_BUILD_HOME}/pegasus
THRIFT_BUILD_HOME=${LOCKERZ_BUILD_HOME}/shared-interface

LOCKERZ_REMOTE=origin
LOCKERZ_BASE_BRANCH=master

cd $(dirname $0)/..
BASEDIR=$PWD
cd - >/dev/null


source $BASEDIR/scripts/functions.sh
