#!/bin/bash

set -e

source $(dirname $0)/include

shift $(($OPTIND - 1))

if test $# -lt 2 ; then
  fatal "two arguments are required"
fi

MESSAGE=$1
COLOR=$2
curl -d "room_id=Production&from=Deploy+Bot&message=${MESSAGE}&notify=1&color=${COLOR}" "https://api.hipchat.com/v1/rooms/message?format=json&auth_token=6d74e531d5769cb05baee432c36b23" > /dev/null 2>&1
