#!/usr/bin/python
import sys
import re

mod_next_line = False
for line in sys.stdin:
    if mod_next_line:
        sys.stdout.write(re.sub("\d+\.\d+\.\d+", sys.argv[1], line))
        mod_next_line = False
    else:
        sys.stdout.write(line)
            
    if line.strip() == "assets_base_urls:":
        mod_next_line = True


