#!/bin/bash

set -e 
source $(dirname $0)/include

shift $(($OPTIND - 1))

if test $# -lt 1; then
    fatal "One argument, the version number, is required"
fi

VERSION=$1
GIT_TAG="${VERSION}"

git tag -a ${GIT_TAG} -m "Release of version ${VERSION}"
git push ${LOCKERZ_REMOTE} ${GIT_TAG}
