// Code generated by protoc-gen-go.
// source: protobuf/MeatShop.proto
// DO NOT EDIT!

package pbs

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Meat struct {
	Id               *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ExpirationDate   *int64   `protobuf:"varint,3,opt,name=expirationDate" json:"expirationDate,omitempty"`
	PriceCents       *int32   `protobuf:"varint,4,opt,name=priceCents" json:"priceCents,omitempty"`
	PictureUrls      []string `protobuf:"bytes,5,rep,name=pictureUrls" json:"pictureUrls,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Meat) Reset()         { *this = Meat{} }
func (this *Meat) String() string { return proto.CompactTextString(this) }
func (*Meat) ProtoMessage()       {}

func (this *Meat) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Meat) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Meat) GetExpirationDate() int64 {
	if this != nil && this.ExpirationDate != nil {
		return *this.ExpirationDate
	}
	return 0
}

func (this *Meat) GetPriceCents() int32 {
	if this != nil && this.PriceCents != nil {
		return *this.PriceCents
	}
	return 0
}

type ListMeatsResponse struct {
	Meats            []*Meat `protobuf:"bytes,1,rep,name=meats" json:"meats,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ListMeatsResponse) Reset()         { *this = ListMeatsResponse{} }
func (this *ListMeatsResponse) String() string { return proto.CompactTextString(this) }
func (*ListMeatsResponse) ProtoMessage()       {}

func init() {
}
